{% set name = "qt-material" %}
{% set version = "2.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/qt-material-{{ version }}.tar.gz
  sha256: b5dbb5ade97217cf7ae336bb7c047c90beb39dc7f2048a498c916ad5f2f7ae23

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - jinja2
    - python >={{ python_min }}

test:
  imports:
    - qt_material
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/UN-GCPDS/qt-material
  summary: Material inspired stylesheet for PySide2, PySide6, PyQt5 and PyQt6.
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
